version: '3.7'

services:
  app:
    build: 
      context: .
    ports:
      - "8000:8000"
    env_file:
      - ./recipeproject/.env
    depends_on:
      - db
  db:
    image: "postgres:15"
    ports:
      - "5432:5432"
    env_file:
      - ./recipeproject/.env
    volumes:
      - recipe-volume:/var/lib/postgresql/data

volumes:
  recipe-volume: